export {default as PartnersSection} from './PartnersSection';
export {default as HowItWorksSection} from './HowItWorksSection';
export {default as LearnMoreSection} from './LearnMoreSection';
export {default as MainHeroSection} from './Hero/HomeHero';
export {default as HeroSection} from './Hero';
export {default as DefaultPageContent } from './DefaultPageContent';
export {default as FAQsection } from './FAQsection';
export {default as ResourcesSection } from './ResourcesSection';
export {default as BenefitsSection } from './BenefitsSection';
export {default as StakingSection } from './StakingSection';
export *  from './requests/index';
