import { useState } from 'react';
import { type NextPage } from 'next';
import Head from 'next/head';
import {
  PartnersSection,
  HowItWorksSection,
  LearnMoreSection,
  MainHeroSection,
} from '../components';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Trip Hut NextJs Template</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainHeroSection />
      <HowItWorksSection />
      <LearnMoreSection />
      <PartnersSection />
    </>
  );
};

export default Home;
